---
- name: Base post-logs
  hosts: localhost
  gather_facts: false
  roles:
    - generate-zuul-manifest
    - role: upload-logs
      vars:
        zuul_log_url: "https://logs.services.betacloud.xyz"
