- name: Start zuul_console daemon.
  zuul_console:

- name: Synchronize src repos to workspace directory.
  synchronize:
    delay_updates: false
    delete: true
    dest: "{{ zuul_workspace_root }}"
    recursive: true
    src: "{{ zuul.executor.src_root }}"
    owner: no
    group: no
